name: LanRPG
main: com.github.lantice3720.LanRPG
version: 1.1.0
description: RPG system add-on
author: lanthanide
api-version: 1.17
commands:
  test:
    description: For..test!
    usage: No Usage. just for test.